### ISSUE TITLE
Logowanie

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#10]
Cześć. 
Chyba wgrałaś bazę. Nie mogę się zalogować.Może nie ma mnie jako użytkownika?
Proszę o Użytkownika
U - slawek
H - Slawek123

Dzięki
Pozdrawiam
Slawek

**Comment by baskap** [comment]
U-Basia

W dniu 18 lutego 2015 08:34 użytkownik szelma007 <notifications@github.com>
napisał:
