### ISSUE TITLE
str. 200 sort 16 pozycji

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#101]
W zakładce "Słowniki" wybieram np. "Formy zajęć" w pole sort wprowadzam co najmniej 16 pozycji i zatwierdzam. Pojawia się komunikat"

Error in mru internal routine: ORA-20001: Error in MRU: row= 1, ORA-01438: value larger than specified precision allowed for this column, update "KRK"."KRK_FORMA_V" set "ID" = :b1, "NAZWA" = :b2, "SORT" = :b3 where "ID" = :p_pk_col
	Error 	Unable to process update.
OK

**Comment by baskap** [comment]
Sławek a nie jest ty powodem duza liczba wpisana do sort, np. 1000000000000?

**Comment by szelma007** [comment]
jest powodem duża ale powyżej 16 cyfr (np.1234567890123456) do 15 cyfr zapisuje bez komunikatu.

**Comment by baskap** [comment]
ok

**Comment by baskap** [comment]
Naprawione
