### ISSUE TITLE
str. 8 pole numer (,)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#103]
W zakładce "Uchwały senatu" podczas dopisywania pozycji w ramce "Efekty kierunkowe i specjalnościowe" w polu numer jeśli się wprowadzi 4,5 zamienia na 45.

**Comment by baskap** [comment]
Kurde chyba zrobiłam :), ale oczywiście stestuj jeszcze

**Comment by szelma007** [comment]
Nie można zapisać nowej pozycji. Jeśli wstawiam nową pozycję np. 25 to po użyciu przycisku "Dodaj efekt kierunkowy" robi się czysta pozycja, ale nie zapisuje (25).
Jeśli zmieniam pozycję o nr np 360 na 27 to po zapisaniu zmian pozostaje pozycja 360.
Przy wpisaniu błędnego numeru (np. 4a; 2,6) po użyciu "Zapisz zamiany" na górze podaje komunikat "Podaj numer efektu kierunkowego'

**Comment by baskap** [comment]
Mam nadzieje ze juz jest ok. Zapomniałam uruchomić proces co zmienia dane w tej tabelce.
