### ISSUE TITLE
str. 256 literatura - sort (minus, zero i przecinek)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#105]
W zakładce "moje przedmioty" dochodzę do opcji "Literatura" w pole "Sort" mogę wprowadzić liczbę ujemną (-7) oraz (0).

Mogę też wprowadzić liczbę (1,6) która podczas zapisywania zamieniana jest na (2). 
To z przecinkiem jest też na ekranie wprowadzania literatury str. 263.

**Comment by szelma007** [comment]
str. 263 podczas wprowadzania nowej pozycji literatury po wprowadzeniu w pole "Sort" 6,6 zaokrągla do 7.

str. 256 na ekranie głównym literatury nogę wprowadzić 0.

**Comment by baskap** [comment]
Mam nadzieję, że już jest ok
