### ISSUE TITLE
str. 15 koordynator dodawanie (pusty)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#107]
W zakładce "Edycje programów" edytuję program (np. Pedagogika specjalność ccc) w ramce "Koordynatorzy programu" mam wybranych 2 koordynatorów i po użyciu przycisku "Dodaj koordynatora programu" pojawia się kolejna (trzecia) pozycja koordynatora. Po użyciu strzałki wyboru wyświetla się pusta ramka.

**Comment by baskap** [comment]
No bo nie ma więcej użytkowników
