### ISSUE TITLE
str 8 Program

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#11]
Uchwała Nr 7, Status niezatwierdzony, Kierunek Politologia

W ramce "Grupa efektów kierunkowych i specjalnościowych" znajduje się przycisk (*Program) do wyboru programu.
Po użyciu strzałki i otworzeniu ramki "Wybierz program" pozwala wybrać dowolny i zmienia (np. Kierunek, typ, itd.). 
Pozwala zapisać zmianę i nie ma Politologii tylko np Informatyka

**Comment by baskap** [comment]
A to tak może być dopóki efekty nie są gdzieś użyte w przedmiotach (o tym jak sie ich uzywa w przedmiotach później). Chodzi tylko o to, żeby dwa razy ten sam program nie był w danej uchwale senatu. Możesz jeszcze w ramach testów stworzyć drugą uchwałę jutro.
