### ISSUE TITLE
str. 255 komunikat (Punkty ECTS i Metryczka)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#110]
Slawek_jazz
Wybieram zakładkę "Moje przedmioty" edytuję "Rozrywkowa gitara" na opcji "Nakład pracy studenta" po prawej stronie znajdują się 3 ramki (Punkty ECTS, Metryczka i Wydruk). 

W ramce "Punkty ECTS" pojawia się komunikat "ORA-01403: no data found "

W ramce "Metryczka" pojawia się komunikat "ORA-20007: Nie ma takiego sylabusu 55544"

**Comment by baskap** [comment]
Na szczęście naprawiłam

**Comment by szelma007** [comment]
U Ciebie nie ma rzeczy nienaprawialnych. :)
