### ISSUE TITLE
str. 31 pole punkty ECTS 

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#111]
Slawek_jazz
Zakładka "Moje edycje programów" wybieram "Pedagogika" tworzę "Nowy przedmiot" w polu "Punkty ECTS" wprowadzam (2,225) daję przycisk "Utwórz" pole "Punkty ECTS" zaokrągla (2,23)

**Comment by baskap** [comment]
Teraz powinno być ok.  Poprawiłam też punkty ECTS w bloku (strona 301).
