### ISSUE TITLE
strona 10 - tworzenie nowej jeednostki

### ISSUE THREAD

**Issue by baskap** [baskap/sylabus#119]
Usunąć przycisk idź do nadrzednego

**Comment by szelma007** [comment]
Jeśli to pytanie to moim zdaniem nie jest on tam potrzebny. 
W samym tworzeniu przycisk nie jest przydatny. Wykorzystywany może być na edycji jednostki (i tu dobrze jakby został).

**Comment by baskap** [comment]
Nie to ja sobie tylko napisałam, zeby pamiętac o zmianie
