### ISSUE TITLE
str. 8 dodaj wiersz

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#12]
W ramce "Efekty kierunkowe i specjalnościowe" w momencie użycia przycisku "Dodaj wiersz" (poza pierwszym wierszem) przenosi ekran na górę do informacji w ramce "Zmieniono 0 wiersz(y), wstawiono 1 wiersz(y), usunięto 0 wiersz(y)."
Może nie musi informować o tym, że wstawiono wiersz a tylko by pozwalał dalej dopisać kolejny wiersz?
Przy dodawaniu np. 9 wiersza trzeba przesuwać ekran na dół i wstawiać kursor w pole "Numer".

Może przycisk "Dodaj wiersz" umieścić poniżej wpisanych wierszy w ramce "Efekty kierunkowe i specjalnościowe". Przy kilkunastu pozycjach nie trzeba będzie przechodzić do góry ramki 
"Efekty kierunkowe i specjalnościowe" żeby  dopisać kolejny wiersz (użyć przycisku "Dodaj wiersz").

**Comment by baskap** [comment]
To na razie niestety tak musi być :(

**Comment by baskap** [comment]
A jednak nie musi :). Proszę stestuj to jeszcze. Po kliknieciu w "Dodaj wiersz"
Kursor powinien zostać przeniesiony do ostatniego wiersza.

**Comment by baskap** [comment]
Zmieniłam dodaj wiersz na "Dodaj efekt kierunkowy"
