### ISSUE TITLE
str. 301 przypisywanie przedmiotu - własne 

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#123]
Zakładka "Moje edycje programów" edytuje program "Pedagogika" wchodzę w opcję "Blok" wybieram "Pomoc społeczna blok" w ramce przypisz przedmiot nie ma przedmiotów własnych.

**Comment by baskap** [comment]
No bo na liście przedmiotów nie ma żadnego stworzonego przedmiotu własnego.

**Comment by szelma007** [comment]
Już widzę, że przedmiot własny i blok jest przypisany do np. specjalności.
