### ISSUE TITLE
str. 31 auto (język wykładowy, wersja językowa sylabusu)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#131]
Zakładka "Przedmioty wspólne" tworzę "Nowy przedmiot" pola "Język wykładowy" i "Wersja językowa sylabusu" pozostają "Auto" przy próbie zatwierdzenia podaje komunikat, że muszą być różne od "auto". Czy nie powinien brać z opcji "ustawień" w "Moje edycje programów"?

**Comment by baskap** [comment]
Nie, bo ustawienia domyślne są przypisane do edycji programu. Przedmioty wspólne mogą być przypisane do różnych edycji, więc muszą mieć to określone oddzielnie.

**Comment by szelma007** [comment]
to info dla mnie 
sprawdzić wydruk w "Moje przedmioty'
