### ISSUE TITLE
str. 304 wydruk siatki - kierunek (bez specjalności)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#133]
Kazik
Na zakładce "Moje edycje programów" mam 5 specjalności (aaa, bbb, ccc, ddd i bez specjalności). Jeśli wejdę w edycję "Pedagogika - bez specjalności" i przejdę na opcję "Wydruki-siatka zajęć" to przy wyborze pola "Kierunek" pojawiają się cztery specjalności pedagogiki (nie ma bez specjalności).

**Comment by baskap** [comment]
Wyjaśnione
