### ISSUE TITLE
str. 304 wydruk siatki -wybranie specjalności

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#134]
kazik
Zakładka "Moje edycje programów" wybieram "Pedagogika - ddd" (w liście przedmiotów mam 1 przedmiot, opcja Blok pusta) przechodzę na wydruk siatki. Przy wyborze kierunku pojawiają się 2 specjalności ddd (moduł wszystkie i ddd-aa) wybieram i daję "Zastosuj". W ramce poniżej podaje też informacje z innych specjalności.

**Comment by baskap** [comment]
Wyjaśnione
