### ISSUE TITLE
str. 8 wydruk 

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#14]
Nie mogę wykonać wydruku z zakładki "Uchwały senatu"

**Comment by baskap** [comment]
Ale jak to się objawia? Bo ja mogę i nie wiem w czym problem

**Comment by szelma007** [comment]
błąd wczytywania strony i komunikat:: 

Przekroczono limit czasu połączenia

Serwer sunik zbyt długo nie odpowiada.

    Witryna może być tymczasowo niedostępna lub zbyt obciążona. Spróbuj ponownie za kilka minut.
    Jeśli nie można otworzyć żadnej strony, należy sprawdzić swoje połączenie sieciowe.
    Jeśli ten komputer jest chroniony przez zaporę sieciową lub serwer proxy, należy sprawdzić, czy program Firefox jest uprawniony do łączenia się z Internetem.

**Comment by baskap** [comment]
A dobra sorry, bo ja tam nie pozmieniałam podczas importu bazy i próbuje sie połączyć z moim komputerem :)
Dziś wieczorem wgram dobrze to będzie działał
