### ISSUE TITLE
str. 8 opis

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#17]
W ramce "Efekty kierunkowe i specjalnościowe" przy wprowadzaniu wierszy pole "Opis" zostawiam puste, a wprowadzam "Opis w języku angielskim". 
Pryz próbie zachowania zmian podaje komunikat: "Podaj opis efektu kierunkowego: Wiersz 3"

**Comment by baskap** [comment]
Opis po polsku jest obowiązkowy, a po angielsku nie. Wiec działa tak jak powinno
