### ISSUE TITLE
str. 8 wprowadzenie samego numeru

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#18]
Jeśli wprowadzę pole "Numer" a nie wprowadzę "Opis" i chcem go usunąć nie mam takiej możliwości (nie ma checkbox'a).
Muszę coś wpisać i dopiero po zapisaniu pojawia się checkbox i moge usunąć wiersz.

Wyjście z ekranu "Grupa efektów kierunkowych i specjalnościowych" powoduje nie zapisanie wiersza.

**Comment by szelma007** [comment]
Ale jak usunę numer to usuwa wiersz

**Comment by baskap** [comment]
Słuchaj teraz już jest checbox obok nowego efektu. Sprawdź czy usuwanie działa dobrze
