### ISSUE TITLE
str. 3 tworzenie nowych kierunków

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#29]
Jeśli w zakładce "Kierunki" wybiorę i wejdę w kierunek np. "Politologia" obejrzę go i  dam przycisk "Anuluj" wrócę na ekran główny zakładki "Kierunek"
Chcę utworzyć nowy kierunek przycisk "Nowy" to przechodzę do tworzenia specjalności na "Politologii".

Nowy kierunek mogę utworzyć po zalogowaniu jeśli nie wejdę w np. "Politologię".

**Comment by szelma007** [comment]
Lub wracając z innej zakładki np. "Programy"

**Comment by baskap** [comment]
Naprawione :) A bład pooważny bardzo
