### ISSUE TITLE
str. 15 zamiana koordynatora

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#32]
Zakładka "Edycje programów" np. Politologia dodaje koordynatora (np. Barbara) zapisuje zmiany obok nazwiska przycisk wyboru (strzałka) pozwala zamienić koordynatora ale przy próbie zapisania podaje komunikat"
"ORA-01445: cannot select ROWID from, or sample, a join view without a key-preserved table"

**Comment by baskap** [comment]
to już nawet wyczaiłam wcześniej sama. Już działa
