### ISSUE TITLE
str. 15 ramka przy koordynatorze

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#33]
Zakładka "Edycje programów" np. Politologia ramka "Koordynatorzy programu" po użyciu przycisku wyboru pojawia się inna ramka (nie taka twoja).

**Comment by baskap** [comment]
No to jest druga opcja - nie można wstawić tej ładnej jak jest tablica rekordów i trzeba korzysać z domyślnej - czyli tak musi zostać
