### ISSUE TITLE
str. 203 słownik tytuły

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#34]
Cześć 

Na nowej uczelni JAZZ zakładka "Słowniki" opcja "Tytuły" są wprowadzone (41 tytułów przypisanych).
Tytuły dopisane na jednej uczelni nie są przenoszone na drugą.

**Comment by baskap** [comment]
One nie powinny byc przenoszone na druga, czyli jest ok :)

**Comment by szelma007** [comment]
A te 41 tytuły są wgrane i przypisane do każdej uczelni?

**Comment by baskap** [comment]
Tak
