### ISSUE TITLE
str.201 słowniki ramka szukania

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#35]
Może do wszystkich 4 słowników dodać ramkę szukania (taką jak jest np. na "Uchwały senatu")

**Comment by baskap** [comment]
Tą ramkę można dodać tylko do "tytułów", bo można ja dodawać tylko jak jest lista,
a "Formy zajęć", "Formy weryfikacji efektów kształcenia", "Formy nakładu pracy studenta"
są formularzem, bo można zmieniać kolumnę "Sort". W tym przypadku mogę dodać tylko pole tekstowe do wyszukiwania nazwy co zaraz zrobię :)

**Comment by baskap** [comment]
Sławek teraz są kryteria filtrowania. Weź to stestuj

**Comment by szelma007** [comment]
Po wpisaniu w filtrowanie nazwy wyszukaniu a następnie przełączeniu się na inny słownik (bez wyczyszczenia wyszukiwania) pozostaje nazwa filtrowana
