### ISSUE TITLE
str.3 dodawanie modułu - przycisk "Utwórz"

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#38]
Zakładka "Kierunki" wybieram np. "Politologia" specjalność "Dziennikarstwo" dopisuje "Moduł specjalności" (np. Polskie) po użyciu przycisku "Utwórz" nie ma możliwości dopisania kolejnego modułu.
trzeba wyjść poziom wyżej i ponownie użyć "Utwórz".

**Comment by baskap** [comment]
Wiesz co to będzie tak rzadko używane, że chyba można zostawić jak jest. Jak myślisz

**Comment by baskap** [comment]
Większość uczelni to w ogóle nie ma modułów.

**Comment by szelma007** [comment]
jak ich jest niedużo to można poczekać czy ktoś będzie miał do tego wątpliwość i coś zgłosi

**Comment by baskap** [comment]
Też mi sie tak wydaje
