### ISSUE TITLE
str 8 wydruk

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#4]
Jeśli nie mam wprowadzonych żadnych pozycji na "Efekty kierunkowe i specjalnościowe" i wykonuje wydruk "Czy drukowć tabelę pokrycia efektów obszarowych? Tak" druga strona wydruku nie zawiera żadnych informacji. 
Na drugiej stronie nie drukuje tabeli "obszar kształcenia..." jest tylko nagłowek i stopka

**Comment by baskap** [comment]
zrobiłam, trza sprawdzić, czy już jest ok
