### ISSUE TITLE
str. 8 odznaczanie "Obszarów kształcenia"

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#48]
W zakładce "Uchwały senatu" wybieram Uchwałę i dodaje grupę (efektów kierunkowych i specjalnościowych) wypełniam ramkę "Grupa efektów kierunkowych i specjalnościowych" przy przycisku "Zachowaj zmiany" odznaczany jest "Obszar kształcenia"

**Comment by baskap** [comment]
To już naprawiłam, ale stestuj jutro jeszcze
