### ISSUE TITLE
str.8 opis 1000 znaków

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#49]
Zakładka "Uchwały senatu" ramka "Efekty kierunkowe i specjalnościowe" pole opis pozwala wprowadzić ponad 1000 znaków. 
Przy próbie zapisania pojawia się komunikat "Opis powinien zawierać mniej niż 1000 znaków Wiersz 1".

Przy opisie w języku angielskim to samo.

**Comment by baskap** [comment]
Wydaje mi się, że naprawiłam, ale przetestuj jeszcze

**Comment by baskap** [comment]
A i daj znać, jak już działa

**Comment by szelma007** [comment]
chyba jest na 100 znaków

**Comment by baskap** [comment]
Jutro będzie 1000
