### ISSUE TITLE
str.8 pole numer (5a)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#50]
Zakładka "Uchwały senatu" ramka "Efekty kierunkowe i specjalnościowe" w pole "Numer" wprowadzam literę (5a) i dodaję efekt kierunkowy pojawia się komunikat:

"ORA-01722: invalid number
	Error 	ERR-1024 Unable to run "function body returning text" validation."

**Comment by baskap** [comment]
Po poprawce jest tak, że "zjadane" są wszystkie znaki, które nie są liczbami.
