### ISSUE TITLE
str. 255 chetbox usuwania

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#60]
Zakładka "Moje przedmioty" opcja "Nakład pracy studenta" w ramce "nakład pracy studenta"przy "forma aktywności studenta" nie ma chetbox'ów do zaznaczenia usunięcia.

**Comment by szelma007** [comment]
można to usunąć w zakładce "Moje edycje programów" opcja  "Lista przedmiotów" ramka "Formy zajęć"

**Comment by szelma007** [comment]
Widzę, że w zakładce "Moje programy" opcja "nakład pracy studenta" w ramce "nakład pracy ..." pojawiają się  dopisywane "Formy aktywności studenta" (np. "Samodzielne studiowanie tematyki zajęć") i t apozycja ma chetbox'a. 
Gdzie to się podaje żeby była widoczna ta pozycja?

**Comment by baskap** [comment]
Generalnie o to chodzi że opiekun edycji programu wpisuje formy zajęć (wykłady, ćwiczenia itp.)
I specjalnie zwykły użytkownik nie ma możliwości zmiany tego, żeby zwykła osoba nie namieszała w planie zajęć

**Comment by baskap** [comment]
A resztę musi uzupełnić prowadzący zajęcia
