### ISSUE TITLE
str. 263 literatura -opuszczanie ekranu

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#68]
W literaturze wprowadzam pozycję (książkę) daje "Utwórz" tworzy się czyste pole do wprowadzania.
Nie wprowadzam następnej pozycji tylko przechodzę na zakładkę np. "Nakład pracy studenta" w ramce błędów na górze pojawia się informacja o konieczności podania autora i tytułu.

Po utworzeniu pozycji używając przycisku "Anuluj" przechodzę o ekran wyżej gdzie mogę dopisać kolejną literaturę (wtedy jest ok).

**Comment by baskap** [comment]
To tak ma działać

**Comment by baskap** [comment]
To znaczy może nie tak ale już naprawiłam
