### ISSUE TITLE
str 8 efekty kierunkowe 

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#7]
W ramce "Efekty kierunkowe i specjalnościowe" po przełączeniu sie na poszczególne zakładki np z Wiedzy na Umiejętności na pasku górnym pojawia się komunikat:

Action Processed

**Comment by baskap** [comment]
Powinno już dzialać dobrze, ale proszę sprawdź to jeszcze raz

**Comment by baskap** [comment]
Jak to działa już poprawnie to zamknij wątek
