### ISSUE TITLE
str. 8 usuwanie efektów kierunkowych

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#72]
Zakładka "Uchwały senatu" dopisałem 2 efekty kierunkowe i użyłem przycisku "Dodaj efekt kierunkowy" mam 3 pozycje (2 wypełnione i 1 pusta).
Chcę usunąć wszystkie 3 pozycje i zaznaczam (wszystkie na raz) chetbox'em obok "Numer", a następnie przycisk "Usun zaznaczone efekty kirunkowe", pojawia się komunikat"
 
ORA-20103: Member sequence 3 does not exist in application collection "EFEKTY_KIERUNKOWE"
	Error 	
OK

**Comment by szelma007** [comment]
jeśli mam tylko 2 pozycje i obie wypełnione to zaznaczenie (wszystkie) i usunięcie działa ok

**Comment by szelma007** [comment]
jeśli pozycję pustą zaznaczę chetbox'em usuń to pojawi się komunikat.
Jeśli jest pusta pozycja i dam usuń bez zaznaczania chetbox'a to usuwa,

**Comment by baskap** [comment]
Powinno być ok od jutra- ale jeszcze sprawdź
