### ISSUE TITLE
str. 30 ramka wydruki - strzałka

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#77]
Zakładka "Moje edycje programów" - "edycja programu" na górze jest ramka wydruki. najechanie i "kliknięcie" na napis "Wydruki" niczego nie powoduje tylko "kliknięcie" na strzałkę rozwija ramkę i daje możliwość wyboru.

**Comment by baskap** [comment]
Zrobiłam, ze przechodzi do siatki zajęć
