### ISSUE TITLE
str. 261 forma zajęć ilość znaków

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#80]
Zakładka "Moje przedmioty" np. Pomoc społeczna opcja "formy zajęć" wybieram np. E-learning. 
Jest ramka "Treść"  przy liczniku treści 3991 of 4000 (w polskim i angielskim) komunikat:

ORA-06503: PL/SQL: Function returned without value
	Error 	ERR-1023 Unable perform validations.
OK

**Comment by baskap** [comment]
bede robić jutro czyli 2015-03-10
