### ISSUE TITLE
str. 255 nakład pracy studenta dodanie liczby godzin

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#83]
Zakładka "Moje przedmioty" wybieram np. Pomoc społeczna opcja "Nakład pracy studenta" dodaje wiersz (np. Konsultacje ) w polach liczba godzin nie ujmuje liczb dziesiętnych (wyrzuca przecinki np. z 62,5 robi 625)

**Comment by szelma007** [comment]
str. 31
W zakładce "Moje edycje programów - Edycja programu - metryczka przedmiotu"  opcja "Lista przedmiotów' ramka "Formy zajęć" tak samo.

**Comment by baskap** [comment]
Zrobiłam, ale sprawdz dokładnie. W polach z godzinami trzeba wpisać liczbe natrualną.
Jak wpisujesz jakąś liczbe i po przecinku same zera to usuwa zera (np.10,000).
Jak po przecinku jest jakaś liczba inna od zera to zaznacza jako błąd (np. 10,5)
Jak jest jakiś znak inny od cyfry to tez zaznacza jako błąd

**Comment by szelma007** [comment]
0 jest dopuszczone.
10 cyfr udało mi się w pisać w polu liczba godzin.

**Comment by baskap** [comment]
Teraz można maksymalnie 5

**Comment by szelma007** [comment]
Na str.31 w zakładce "Moje edycje programów - Edycja programu - metryczka przedmiotu" opcja "Lista przedmiotów' ramka "Formy zajęć" w pole liczba godzin można wprowadzić 10 cyfr.

**Comment by baskap** [comment]
Na 31 stronie naprawiony
