### ISSUE TITLE
str. 30 nowy przedmiot po usunięciu wspólnego

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#87]
Zakładka "Moje edycje programów › Edycja programu" przypisałem przedmiot wspólny (WF) następnie wszedłem do edycji (WF) i usunąłem przypisanie przedmiotu do edycji. Powróciłem do ekranu "Edycja programu" i chciałem utworzyć "Nowy przedmiot" pojawił się komunikat:

ORA-01403: no data found
	Error 	Unable to fetch row.
OK

**Comment by baskap** [comment]
bede robić jutro czyli 2015-03-10
