### ISSUE TITLE
str. 305 pole semestr (*)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#88]
Zakładka "Moje edycje programów › Edycja programu › Przypisane przedmioty wspólne" w ramce "Przedmiot wspólny" przy polu "Semestr" może dodać * (gwiazdkę czerwoną)?
Chyba jest polem wymaganym?
Czy nie zawsze trzeba podawać ?

**Comment by baskap** [comment]
Zawsze trzeba
