### ISSUE TITLE
str 8 obszary kształcenia

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#9]
Pomimo zatwierdzenia pozwala zaznaczać i odznaczać pozycje

**Comment by baskap** [comment]
Ale jakie pozycje?

**Comment by szelma007** [comment]
Nauki humanistyczne, Nauki ścisłe, nauki techniczne itd.

**Comment by szelma007** [comment]
w ramce "Grupa efektów kierunkowych i specjalnościowych"
