### ISSUE TITLE
str. 304 wydruk siatki - nazwy zajęć (pion)

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#92]
Przy wydruku (PDF) siatki w pionie nie wyświetla nazw form zajęć (wykład, ćwiczenia, laboratorium, itd.). Jeśli będzie dużo form przypisanych do przedmiotu to i tak nazwy mogą się nie mieścić.

**Comment by baskap** [comment]
Nie ma wgranego oprogramowania do birt do odwracania na serwerze - to jest powód.
Zaraz wgram
