### ISSUE TITLE
str. 304 komunikat po wejściu w przedmiot na wydruku siatki 

### ISSUE THREAD

**Issue by szelma007** [baskap/sylabus#94]
Zakładka "Moje edycje programów" wybieram kierunek "Polityka społeczna" opcję "wydruki" (siatka zajęć) wybieram kierunek "Polityka społeczna - niestacjonarne).
W ramce "Siatka zajęć" jest nazwa przedmioty (podkreślona) po wejściu w "pomoc społeczna lub pomoc finansowa" przechodzi na nową stronę i podaje komunikat: 

HTTP Status 404 - Not Found

type Status report

message Not Found

description The requested resource is not available.
Apache Tomcat/7.0.37

**Comment by baskap** [comment]
To tez na pózniej
